language: node_js
node_js:
- '14'
cache:
  directories:
  - node_modules
install:
- npm install
jobs:
  include:
  - stage: build
    script: npm run test && npm run build
    on:
      branch: master
  - stage: pr-build
    if: "(type IN (pull_request))"
    script: npm run test && npm run build
  - stage: deploy
    if: tag IS present
    script: npm run test && npm run build
    deploy:
      provider: npm
      email: OpenDevWG@t-mobile.com
      api_key:
        secure: PYnLnG0agI6T/Mv3qkr9V/Ryp/ytry27fHDuQnPhyKrOfKb9mo6ohNRUciFW3GEs53rmxkZ6xp/vDKTe5+OVxAd0XOTJJKb9KHosSgnD8Lv2rVUfoyckYhzyCsMoDM5zehJAbNWtczI69uxLF4GoVqsCi88+/7m+R8MUbdH9ZM1uWeo/JzAcKet8dVmoH9ucEvKsGE52BMqKkhdZxINdMZkVOd3HhVSdaClRRbGJPqFZiA4e3eWSnPGL0ZcvgOPenI1O5hiQN7BlXhZH6zZI1iZgOSWSYvnHwBK74nl+6FqXq+ssuiiN9+ILA+hwgb+Z3s0a8SJCZrGb4HUphk3O30Za/5K54iHE8QtM3JKuiCTG7HBjF2UYN21FBYzeYtA83OIdZA16Vpz+pHeHAnk3rsc39KVlaO7Ec2ZPUQRoFkGwAVwkUpdI8y4KbmwYjad/BbrsbaVQcjTlIg0cYPcIgD6nWXG+W5c2virpFT+b0JJQIJB3hh3qcAKZqwQvo6YV++3g9DLaBzSx4vpjhdjdd+rEvLAJjnyrucwZSpDaipAeB5kic9rLi/Mq9W+dmWWSlJ/OQcDmRLCoeU4FDnL+eHb3RMZ6aB11oTwxasVfvGrKMGdSYMGgREne/+xZV4NhbK3HgC+wEIRzh+Duy+fXGVaiuZsjX3IW4V2OUugSBVc=
      on:
        tags: true
      skip_cleanup: true
